[package]
name = "cch23-drc"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.3.1"
serde = {version = "1.0", features = ["derive"]}
shuttle-actix-web = "0.35.0"
shuttle-runtime = "0.35.0"
tokio = "1.26.0"
fancy-regex = "0.12.0"
lazy_static = "1.4.0"
